[mypy]
python_version = 3.13
plugins = mypy_django_plugin.main
follow_imports = silent
warn_unused_configs = True
exclude = (^|/)(polls/migrations|static)/

[mypy.plugins.django-stubs]
django_settings_module = mysite.settings
