# Generated by Django 6.0.3 on 2026-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('place', models.CharField(choices=[('HOME', 'Casa'), ('GYM', 'Gym'), ('BOTH', 'Casa y gym')], default='BOTH', max_length=8)),
                ('goal', models.CharField(choices=[('LOSE_FAT', 'Perder grasa'), ('GAIN_MUSCLE', 'Ganar musculo'), ('STRENGTH', 'Fuerza'), ('ENDURANCE', 'Resistencia'), ('MOBILITY', 'Movilidad')], max_length=20)),
                ('level', models.CharField(choices=[('BEGINNER', 'Principiante'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], default='BEGINNER', max_length=20)),
                ('focus_area', models.CharField(default='Cuerpo completo', max_length=80)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('requires_equipment', models.BooleanField(default=False)),
                ('equipment_notes', models.CharField(blank=True, max_length=140)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['duration_minutes', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
