# Generated by Django 6.0.3 on 2026-03-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_exercise_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='focus_area',
            field=models.CharField(default='Full body', max_length=80),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('LOSE_FAT', 'Lose fat'), ('GAIN_MUSCLE', 'Build muscle'), ('STRENGTH', 'Strength'), ('ENDURANCE', 'Endurance'), ('MOBILITY', 'Mobility')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='place',
            field=models.CharField(choices=[('HOME', 'Home'), ('GYM', 'Gym'), ('BOTH', 'Home and gym')], default='BOTH', max_length=8),
        ),
    ]
