# Generated by Django 6.0.3 on 2026-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_exercise_focus_area_alter_exercise_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='impact',
            field=models.CharField(choices=[('LOW', 'Low impact'), ('MODERATE', 'Moderate impact'), ('HIGH', 'High impact')], default='MODERATE', max_length=8),
        ),
    ]
