# Generated by Django 6.0.3 on 2026-03-10 18:51

from django.db import migrations, models


def classify_existing_exercise_language(apps, schema_editor):
    Exercise = apps.get_model("polls", "Exercise")

    for exercise in Exercise.objects.all().iterator():
        description = (exercise.description or "").lower()
        if description.startswith("step:") or description.startswith(
            "ejercicio importado de exercisedb"
        ):
            exercise.content_language = "en"
        else:
            exercise.content_language = "es"
        exercise.save(update_fields=["content_language"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_exercise_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="content_language",
            field=models.CharField(
                choices=[("es", "Spanish"), ("en", "English")],
                default="es",
                max_length=2,
            ),
        ),
        migrations.RunPython(
            classify_existing_exercise_language,
            reverse_code=noop_reverse,
        ),
    ]
